# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "07e8a036-9dc4-4904-ab30-d2f6664c77ba"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  gradle(task: "assembleDevelopRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: Wasabeef
    api_token: "*************",
    build_secret: "***************************"
  )
end
